CREATE USER 'mymeal_admin'@'localhost' IDENTIFIED BY 'u9wZpVbs7xbD45JR';
GRANT USAGE ON *.* TO 'mymeal_admin'@'localhost' IDENTIFIED BY 'u9wZpVbs7xbD45JR';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `mymeal`.* TO 'mymeal_admin'@'localhost';
